apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-single-secret
spec:
  replicas: 2
  selector:
    matchLabels:
      app: env-single-secret
  template:
    metadata:
      labels:
        app: env-single-secret
    spec:
      containers:
        - name: kubecluster-ab68
          image: bimalvasan.azurecr.io/kubecluster
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: test-secret
          ports:
            - containerPort: 8080
